apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  root-username: my-secret-username
  root-password: my-super-secure-password
  db-name: top-secret-db-name
  db-config-host: very-secret-hostname
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
data:
  flask-secret-key: my-long-and-hard-to-guess-flask-secret-key
