name: userapi CICD
on:
  push:
    branches:
      - main
    paths:
      - userapi/**
jobs:
  # build and test
  build_test:
    defaults:
      run:
        working-directory: userapi/app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8","3.9"]
    steps:
        # check out the repository
      - name: checkout_code
        uses: actions/checkout@v2
        # set up python versions matrix
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # run the unittests
      - name: run unittest
        run: |
          python -m unittest
  # deploy to Heroku
  deploy:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # community workflow to bypass link Github in Heroku (feature unavailable due to security incident)
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "my-stupid-flask-api"  
          heroku_email:  ${{secrets.HEROKU_EMAIL}}
          appdir: "userapi/app"
